RetroRabbit/RGO-Server

- RGO.App.Tests/Controllers/HRIS/EmployeeControllerUnitTests.cs
Completed the employee controller unit test with 100% coverage.
- Completed the success and fail tests for GetEmployeesCount method
- Completed the success and fail tests for GetChurnRate method
> Employee controller unit test

- HRIS.Models/ChartRoleLinkDto.cs
- HRIS.Models/EmployeeBankingDto.cs
- HRIS.Models/FieldCodeDto.cs
- HRIS.Models/FieldCodeOptionsDto.cs
- HRIS.Models/SimpleEmployeeBankingDto.cs
- HRIS.Services.Tests/Services/AuthServiceUnitTest.cs
- HRIS.Services.Tests/Services/FieldCodeOptionsServiceUnitTests.cs
- HRIS.Services.Tests/Services/FieldCodeServiceUnitTests.cs
- HRIS.Services/Services/EmployeeBankingService.cs
- HRIS.Services/Services/FieldCodeService.cs
- RR.App.Tests/Controllers/HRIS/EmployeeBankingControllerUnitTests.cs
- RR.App.Tests/Controllers/HRIS/FieldCodeControllerUnitTests.cs
- RR.App/Controllers/HRIS/EmployeeBankingController.cs
- RR.Tests.Data/Models/HRIS/EmployeeBankingTestData.cs
- RR.UnitOfWork.Tests/Entities/EmployeeDataUnitTests.cs
- RR.UnitOfWork.Tests/Entities/FieldCodeOptionsUnitTests.cs
- RR.UnitOfWork.Tests/Entities/FieldCodeUnitTests.cs
- RR.UnitOfWork.Tests/Entities/PropertyAccessUnitTests.cs
- RR.UnitOfWork/Entities/HRIS/ChartRoleLink.cs
- RR.UnitOfWork/Entities/HRIS/EmployeeBanking.cs
- RR.UnitOfWork/Entities/HRIS/FieldCode.cs
- RR.UnitOfWork/Entities/HRIS/FieldCodeOptions.cs
Also did auth key occurrence fix
> FieldCodeDto, FieldCodeOptions,ChartRoleLinkDto and EmployeeBankingDTO refactor

- HRIS.Models/PolicySettings.cs
- HRIS.Models/RoleAccessDto.cs
- HRIS.Models/SimpleEmployeeBankingDto.cs
- HRIS.Models/SimpleEmployeeDocumentDto.cs
- HRIS.Services.Tests/Services/RoleAccessLinkServiceUnitTest.cs
- HRIS.Services.Tests/Services/RoleAccessServiceUnitTest.cs
- RR.App.Tests/Controllers/HRIS/RoleManageControllerUnitTests.cs
- RR.App/Controllers/HRIS/RoleManageController.cs
- RR.App/Program.cs
- RR.Tests.Data/Models/HRIS/EmployeeDocumentTestData.cs
- RR.UnitOfWork.Tests/Entities/RoleAccessLinkUnitTests.cs
- RR.UnitOfWork.Tests/Entities/RoleAccessUnitTests.cs
- RR.UnitOfWork/Entities/HRIS/RoleAccess.cs
> Add refactor Simple Employee Document DTO
>  Refactoring Simple Employee Document DTO

- HRIS.Models/EmployeeEvaluationInput.cs
- HRIS.Services.Tests/Services/EmployeeEvaluationAudienceServiceUnitTests.cs
- HRIS.Services.Tests/Services/EmployeeEvaluationRatingServiceUnitTests.cs
- HRIS.Services.Tests/Services/EmployeeEvaluationServiceUnitTests.cs
- HRIS.Services/Services/EmployeeEvaluationRatingService.cs
- HRIS.Services/Services/EmployeeEvaluationService.cs
- RR.App.Tests/Controllers/HRIS/EmployeeEvaluationAudienceControllerUnitTests.cs
- RR.App.Tests/Controllers/HRIS/EmployeeEvaluationControllerUnitTests.cs
- RR.App.Tests/Controllers/HRIS/EmployeeEvaluationRatingControllerUnitTests.cs
- Add refactor the employee evolution input
> Employee evaluation input

- RR.App/Controllers/HRIS/EmployeeController.cs
TALENT ROLE:
=====================================
JOURNEY ROLE:
=====================================
ADMIN ROLE:
=====================================
SUPERADMIN ROLE:
=====================================
> Policy change employees/count endpoint

- RR.App.Tests/Controllers/HRIS/ChartControllerIntegrationTest.cs
- RR.App.Tests/Controllers/HRIS/ChartControllerUnitTests.cs
- RR.App/Controllers/HRIS/ChartsController.cs
- RR.UnitOfWork/RR.UnitOfWork.csproj
-  Add integration test on the chart controller integration test
> Integration Test

- HRIS.Services/Interfaces/IEmployeeService.cs
- HRIS.Services/Services/EmployeeService.cs
- RR.App/Controllers/HRIS/EmployeeController.cs
ADDING NEW EMPLOYEE WITH DUPLICATE ID:
===============================
ADDING NEW EMPLOYEE WITH NEW ID:
==========================
UPDATING PROFILE WITH NEW ID:
==========================
UPDATING PROFILE WITH EXISTING ID:
==========================
UPDATING PROFILE WITH OWN ID:
==========================
> Check duplicate ID Numbers on the system

- HRIS.Services.Tests/Services/ChartServiceUnitTests.cs
- HRIS.Services/Services/ChartService.cs
- RR.App.Tests/Controllers/HRIS/EmployeeBankingControllerIntegrationTests.cs
- RR.Tests.Data/Models/HRIS/EmployeeTestData.cs
- RR.Tests.Data/Models/HRIS/EmployeeTypeTestData.cs
- RR.UnitOfWork/Entities/HRIS/Employee.cs
Back-end and Front-End Functionality Tested- Coverage Report below
> Fixed Chart Service Unit Test and Employee API

- HRIS.Models/Enums/FileCategory.cs
- HRIS.Services.Tests/Handler/Charts/AgeTypeUnitTest.cs
Adding employee document values to FileCategory enum
Unit test Fix - GenerateDataDobTestSuccess in AgeTypeUnitTest File:
> Employee documents enum values

- HRIS.Services.Tests/Services/EmployeeQualificationServiceUnitTests.cs
This pull request adds comprehensive unit tests for the EmployeeQualificationService class, enhancing the overall test coverage and ensuring the robustness of the service methods.
Added EmployeeQualificationServiceUnitTests.cs
- SetupEmployeeExists(): Configures mock behavior for an existing employee.
- SetupEmployeeDoesNotExist(): Configures mock behavior for a non-existent employee.
- SetupLogException(): Configures mock behavior for logging exceptions.
- VerifyLogExceptionCalled(Times times): Verifies the number of times the exception logging was called.
- VerifyGetEmployeeByIdCalled(Times times): Verifies the number of times GetEmployeeById was called.
- VerifyAddQualificationCalled(Times times): Verifies the number of times a qualification was added.
- …
> DEV | Employee Qualification Service Unit Test

- HRIS.Models/Enums/DocumentType.cs
- HRIS.Services/Services/EmployeeDocumentService.cs
Added custom field Type to the enums.
> Custom Document Type Added

- HRIS.Models/WorkExperienceDto.cs
- HRIS.Services.Tests/Services/WorkExperienceServiceUnitTest.cs
- HRIS.Services/Services/WorkExperienceService.cs
- RR.App.Tests/Controllers/HRIS/WorkExperienceControllerUnitTest.cs
- RR.UnitOfWork/Entities/HRIS/WorkExperience.cs
- RR.UnitOfWork/Migrations/20240522090140_updatedWorkExperienceCRUD.Designer.cs
- RR.UnitOfWork/Migrations/20240522090140_updatedWorkExperienceCRUD.cs
**Details:**
Update the fields of the work experience entity so it can fit the new designs made for the Work Experience Accordion.
**Affected fields**
- Title -> Client Name
- Employment Type -> Project Name
- Company Name -> Skill Set
- Location -> Software
**Updated coverage reports:**
> Updated Work Experience Fields to accompany new designs

- HRIS.Models/EmployeeSalaryDetailsDto.cs
- RR.Tests.Data/Models/HRIS/EmployeeSalaryDetailsTestData.cs
- RR.UnitOfWork/Entities/HRIS/EmployeeSalaryDetails.cs
- RR.UnitOfWork/Migrations/20240522112841_addDateToSalaryDetails.Designer.cs
- RR.UnitOfWork/Migrations/20240522112841_addDateToSalaryDetails.cs
Added new field to Employee Salary Details entity to include the date when data on the Salary Details accordion has been changed.
> Updated EmployeeSalaryDetailsDto

- RR.App/Controllers/HRIS/EmployeeController.cs
- RR.App/appsettings.json
Updating permissions for Journey Role so that they can add an employee
> Update Policies Permissions for Journey

- HRIS.Services.Tests/Services/EmployeeSalaryDetailsServiceUnitTests.cs
- HRIS.Services/Services/EmployeeSalaryDetailsService.cs
- RR.App.Tests/Controllers/HRIS/EmployeeSalaryDetailsControllerUnitTests.cs
- RR.App/Controllers/HRIS/EmployeeSalaryDetailsController.cs
I have added the Unit Tests for both the Controller and Service of EmployeeSalaryDetails. All my tests are passing, and I have added screenshots of the coverage reports of said Unit Tests.
> Adding Controller and Service Unit Tests for EmployeeSalaryDetails

- HRIS.Services.Tests/Services/EmployeeDocumentServiceUnitTest.cs
> Parameterizing the document save unit test 100% coverage

- RR.App.Tests/Controllers/HRIS/EmployeeDocumentControllerUnitTest.cs
- RR.Tests.Data/Models/HRIS/EmployeeDocumentTestData.cs
- Add complete the Employee Document Controller 
Unit Test
> Add complete the EmployeeDocumentControllerUnitTest

- HRIS.Services/Services/EmployeeService.cs
Added fix so new added employee no longer shows resigned 
- end employment button alignment will be fixed in reinos pr
> added flag

- RR.App/Controllers/HRIS/WorkExperienceController.cs
Employee Id was changed on the work Experience Controller.
> Hot fix for EmployeeId Work Experience

- HRIS.Services/Services/EmployeeDocumentService.cs
- RR.UnitOfWork/Entities/HRIS/EmployeeDocument.cs
Amended Status incorrectly updated
Amended Docdto to send doctype3
> Starterkit Docs

- RR.App/Controllers/HRIS/EmployeeRoleManageController.cs
Roles that were being changed on the drop down menu under Employees tab were getting removed upon changing them.
When a user that had their role changed tried to login, they would default to employee role.
**Solution:**
Before the role is removed, the role id is first checked if it exists in the database. If it does not exist. Then return a Not Found response. If it does exist then remove the previous role and add the new role to the user.
[Bug 9499](https://dev.azure.com/retro-rabbit/RetroGradOnboard/_sprints/taskboard/RetroGradOnboard%20Team/RetroGradOnboard/Sprint%2023?workitem=9499)
> DEV | Roles Not Reflecting Change

- HRIS.Services/Services/AuthService.cs
- HRIS.Services/Services/TerminationService.cs
- Removed the conditional check from termination service
- Added check on auth service to check if the user exists on auth0 before deleting the user
- No unit tests were broken with the change and still passes
> Updated the delete method on the authservice and removed check from the termination service

- RR.App.Tests/Controllers/HRIS/EmployeeBankingControllerIntegrationTests.cs
- RR.App.Tests/Controllers/HRIS/EmployeeQualificationControllerUnitTests.cs
- RR.App/Controllers/HRIS/EmployeeQualificationController.cs
- RR.Tests.Data/AuthorizeIdentityMock.cs
- Tested the accordion that uses the end points all good
- Tested the endpoint via swagger 
- updated unit tests so all are passing
- Eduan told me we can look at the integration tests later as the middleware might be causing some funky issues there.
There are two lines of two of the if statements that are yellow preventing max coverage if someone has any suggestions or potential fixes 👍🏻
> Employee qualification controller refactor/and test update

- HRIS.Services.Tests/Services/EmployeeQualificationServiceUnitTests.cs
- HRIS.Services/Interfaces/IEmployeeQualificationService.cs
- HRIS.Services/Services/EmployeeQualificationService.cs
- HRIS.Services/Services/EmployeeService.cs
- RR.App.Tests/Controllers/HRIS/EmployeeQualificationControllerUnitTests.cs
- RR.App/Controllers/HRIS/EmployeeQualificationController.cs
- RR.Tests.Data/Models/HRIS/EmployeeQualificationTestData.cs
Refactoring of Employee Qualification Service
> Refactoring Employee Qualification Service

- RR.App.Tests/Controllers/HRIS/EmployeeDocumentControllerUnitTest.cs
- RR.App/Controllers/HRIS/EmployeeDocumentController.cs
- RR.Tests.Data/Models/HRIS/EmployeeDocumentTestData.cs
> document controller refactor

- HRIS.Services/Services/ChartService.cs
- RR.App.Tests/Controllers/HRIS/ChartControllerUnitTests.cs
- RR.App.Tests/Controllers/HRIS/EmployeeBankingControllerIntegrationTests.cs
- RR.App/Controllers/HRIS/ChartsController.cs
**Coverage Report:**
- Removed all logic from the controller
- Updated the service to handle all the logic
- Updated the unit tests and removed unnecessary tests
- All exceptions will be handled by the middleware that has been implemented
> Charts controller refactor with Unit test and Service updates

- RR.App/Program.cs
The Main method was over 200 lines. We needed to refactor the setup code.
Place them in their own related methods so its not hard to follow the code.
**Note: Please test on your side before approval.**
[Dev 9572](
https://dev.azure.com/retro-rabbit/RetroGradOnboard/_boards/board/t/RetroGradOnboard%20Team/Stories?System.AssignedTo=%40me&workitem=9572)
> Dev | Program.cs Refactor

- RR.App.Tests/Controllers/HRIS/EmployeeControllerUnitTests.cs
- RR.App/Controllers/HRIS/EmployeeController.cs
> Employee controller refactor
